# 隐藏文章
excludePost: []
todo:
  - 🧩 尝试一个人做个全生态node版ioc框架?
  - 📃 前端的配置文件繁多, 能不能做一个web ui来管理这些配置文件? 只要一个npx命令就可以进入这个web ui? 然后再加个插件系统, web ui里再加个插件市场?
  - 🎵 YesCloudMusic的制作
  - 📅 完善博客...长期任务喵
  - ✨ 9月份, 新版鸿蒙腕上RSS
