/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    InfoItem: typeof import('./components/InfoItem.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverOverlay: typeof import('@headlessui/vue')['PopoverOverlay']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    PopoverText: typeof import('./components/PopoverText.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
