/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/now/2024-06': RouteRecordInfo<'/now/2024-06', '/now/2024-06', Record<never, never>, Record<never, never>>,
    '/posts/2024-first-half-trifles': RouteRecordInfo<'/posts/2024-first-half-trifles', '/posts/2024-first-half-trifles', Record<never, never>, Record<never, never>>,
    '/posts/apple-watch-2023': RouteRecordInfo<'/posts/apple-watch-2023', '/posts/apple-watch-2023', Record<never, never>, Record<never, never>>,
  }
}
